# Generated by Django 3.0.8 on 2020-10-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('Date', models.DateField(auto_now=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
