# Generated by Django 3.0.8 on 2020-10-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
