# Generated by Django 3.0.8 on 2020-10-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20201028_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='View',
            field=models.IntegerField(default=0),
        ),
    ]
