# Generated by Django 3.0.8 on 2020-10-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=100000000)),
                ('summary', models.TextField()),
                ('featured', models.BooleanField()),
                ('Email', models.EmailField(max_length=100)),
                ('upload', models.FileField(upload_to='C:\\Users\\chidalu craving\\upload')),
            ],
        ),
    ]
