# Generated by Django 3.0.8 on 2020-10-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upload',
            field=models.FileField(upload_to='C:\\Users\\chidalu craving\\Sofware development\\Django\\trydjango\\src\\djangopro'),
        ),
    ]
